import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Јади домашно</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Здраво!</p>
        <p className="font-bad-script">Свету!</p>
      </main>
    </>
  );
}
